#!/usr/bin/env bash
#
# bootstrap installs things.

# NOTE(agronskiy): mostly copy-paster from @andreibarsan/dotfiles

set -eo pipefail

cd "$(dirname "$0")/.."
DOTFILES=$(pwd -P)

echo

# This just contains logging functions
source $DOTFILES/zsh/logging.explicit-load.zsh

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

        local currentSrc=$(readlink "$dst")

        if [ "$currentSrc" == "$src" ]
        then

            skip=true;

        else

            log_user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
            [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
            read -n 1 action </dev/tty

            case "$action" in
            o )
                overwrite=true;;
            O )
                overwrite_all=true;;
            b )
                backup=true;;
            B )
                backup_all=true;;
            s )
                skip=true;;
            S )
                skip_all=true;;
            * )
                ;;
            esac
        fi
    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      log_success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      log_success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      log_success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    log_success "linked $1 to $2"
  fi
}

install_dotfiles () {
    log_info 'installing dotfiles'

    local overwrite_all=false backup_all=false skip_all=false

    local verbose=${DOTFILES}/_verbose/

    find -H "$DOTFILES" -maxdepth 10 -name "*.symlink" -not -path '*.git*' -print0 | while IFS= read -r -d '' src; do
        if [[ "$src" == *'/_verbose/'* ]]; then
            # We assume everything in our '_verbose' dir should actually be linked
            # mirroring the exact directory structure into our home dir.

            dir="$(dirname "${src:${#verbose}}")"
            mkdir -p "$HOME/$dir"

            # Also, we no longer auto-add the dot in front of the filename.
            dst="$HOME/$dir/$(basename "${src%.*}")"
        else
            # Everything not in '.config' will be linked directly into $HOME, with
            # a '.' automatically added to the file name.
            dst="$HOME/.$(basename "${src%.*}")"
        fi
        link_file "$src" "$dst"
    done
}

# Suport locally installing things.
mkdir -p "${HOME}/bin"
mkdir -p "${HOME}/lib"
mkdir -p "${HOME}/man"
mkdir -p "${HOME}/include"

install_dotfiles

log_info "Installing dependencies (./bin/dotfiles-main)"
if source ./bin/dotfiles-main;
then
    log_success "Dependencies installed (./bin/dotfiles-main)"
else
    log_fail "Error installing dependencies (./bin/dotfiles-main)"
fi

echo ''
log_success '  All installed!'
