#!/usr/bin/env bash
#
# bootstrap installs things.

# NOTE(agronskiy): mostly copy-paster from @andreibarsan/dotfiles

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

        local currentSrc="$(readlink $dst)"

        if [ "$currentSrc" == "$src" ]
        then

            skip=true;

        else

            user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
            [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
            read -n 1 action </dev/tty

            case "$action" in
            o )
                overwrite=true;;
            O )
                overwrite_all=true;;
            b )
                backup=true;;
            B )
                backup_all=true;;
            s )
                skip=true;;
            S )
                skip_all=true;;
            * )
                ;;
            esac
        fi
    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
    info 'installing dotfiles'

    local overwrite_all=false backup_all=false skip_all=false

    local verbose=${DOTFILES_ROOT}/_verbose/

    find -H "$DOTFILES_ROOT" -maxdepth 8 -name "*.symlink" -not -path '*.git*' -print0 | while IFS= read -r -d '' src; do
        if [[ "$src" == *'/_verbose/'* ]]; then
            # We assume everything in our '_verbose' dir should actually be linked
            # mirroring the exact directory structure into our home dir.

            dir="$(dirname "${src:${#verbose}}")"
            mkdir -p "$HOME/$dir"

            # Also, we no longer auto-add the dot in front of the filename.
            dst="$HOME/$dir/$(basename "${src%.*}")"
        else
            # Everything not in '.config' will be linked directly into $HOME, with
            # a '.' automatically added to the file name.
            dst="$HOME/.$(basename "${src%.*}")"
        fi
        link_file "$src" "$dst"
    done
}

# Suport locally installing things.
mkdir -p "${HOME}/bin"
mkdir -p "${HOME}/lib"
mkdir -p "${HOME}/man"
mkdir -p "${HOME}/include"

# setup_gitconfig

# If we're on a Mac, let's install and setup homebrew together with a bunch
# of commong useful packages. This is done *before* the bits and bobs, since we
# may need some of these tools (e.g., cmake) for installing bits and bobs.
# if [ "$(uname -s)" == "Darwin" ]; then
#   info "installing dependencies"
#   if source bin/dot | while read -r data; do info "$data"; done
#   then
#     success "dependencies installed"
#   else
#     fail "error installing dependencies"
#   fi
# else
#   # Naively assume Ubuntu/Debian and install some misc. stuff.

#   # TODO(agronskiy): add here the linux installation procedure
# fi

install_dotfiles

echo ''
echo '  All installed!'
